[package]
name = "{{projectName}}"
version = "1.0.0"
authors = []

[addresses]
counter = "_"

[dev-addresses]
# Dev addresses for testing (used with movement move test --dev)
# These addresses are temporary and used for local development/testing only
counter = "0xcafe"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]