[package]
name = "{{projectName}}"
version = "1.0.0"
authors = []

[addresses]
counter = "_"

[dev-addresses]
# Dev addresses are auto-detected by movehat during compilation
# You can also add them manually here if needed

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]